### ISSUE TITLE
Unable to create Schemas due to lowercase property types

### ISSUE THREAD

**Issue by ctuckz** [microsoftgraph/msgraph-sdk-serviceissues#55] opened 2021-02-01 22:35 UTC
### Expected behavior
Should be able to create a schema for an external connection using the SDK: https://docs.microsoft.com/en-us/graph/api/externalconnection-post-schema?view=graph-rest-beta&tabs=java

### Actual behavior
Receive a 400 error due to the `type` field of the properties being lowercase:
```
{
    "error": {
        "code": "InvalidRequest",
        "message": "The request is malformed or incorrect.",
        "innerError": {
            "code": "DeserializationError",
            "message": "Requested value 'string' was not found.",
            "date": "2021-02-01T21:58:17",
            "request-id": "2d4c7212-5e51-4327-8c8c-8c8f1a200529",
            "client-request-id": "30148d93-4433-4391-abb1-3ea4ffdce1fd"
        }
    }
}
```

### Steps to reproduce the behavior
Using 0.3.0-SNAPSHOT, although I saw the same behavior in 0.1.0

1. Create a new `Schema` object
2. Attempt to create a schema using the SDK: `client.external().connections(connectionId).schema().buildRequest().post(newSchema)`
3. The request uses lowercase types for properties and returns the 400 error above:
```
{
    "baseType": "microsoft.graph.externalItem",
    "properties": [
        {
            "isQueryable": false,
            "isRefinable": false,
            "isRetrievable": false,
            "isSearchable": false,
            "name": "id",
            "type": "string"
        },
        {
            "isQueryable": true,
            "isRefinable": false,
            "isRetrievable": true,
            "isSearchable": true,
            "labels": ["title"],
            "name": "name",
            "type": "string"
        },
        ...
    ]
}
```
4. Modify the request body so that the property types start with uppercase letters, and manually send the request using curl or postman:
```
{
    "baseType": "microsoft.graph.externalItem",
    "properties": [
        {
            "isQueryable": false,
            "isRefinable": false,
            "isRetrievable": false,
            "isSearchable": false,
            "name": "id",
            "type": "String"
        },
        {
            "isQueryable": true,
            "isRetrievable": true,
            "isSearchable": true,
            "labels": ["title"],
            "name": "name",
            "type": "String"
        },
        ...
    ]
}
```
5. The request now succeeds and the schema is created

 
[AB#7929](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7929)

**Comment by baywet** [comment] 2021-02-02 14:09
Hi @ctuckz 
Thanks for reaching out.
This issue is caused by the fact this enumeration is not following OData conventions on the service side.
It should be defined (and accept) lower camel casing but it's defined using upper camel casing. (search for `Int64Collection` in [the metadata](https://graph.microsoft.com/beta/$metadata))

I'll try to get in touch with the service team so they can address that.

**Comment by baywet** [comment] 2021-02-02 14:30
for internal readers: this seams to belong to jkatti's team, reached out internally.

**Comment by baywet** [comment] 2021-02-02 17:39
update: the service team is working on it.

**Comment by ctuckz** [comment] 2021-02-02 19:03
Thanks for looking into this so quickly @baywet!

**Comment by ctuckz** [comment] 2021-02-25 01:28
Hey @baywet, do you have a rough ETA for when this will be fixed?

**Comment by baywet** [comment] 2021-02-25 16:07
@ctuckz thanks for the reminder. I just chatted with the service team. Their answer was "2 weeks".

**Comment by baywet** [comment] 2021-03-11 21:14
@ctuckz the service has been fixed from what I can see, can you give it another try and let me know the result please?

**Comment by ctuckz** [comment] 2021-03-15 23:26
Hey @baywet, everything seems to be working correctly when I try it too. Thanks for fixing this!

**Comment by baywet** [comment] 2021-03-15 23:32
Thanks for letting us know! Closing.

**Closed as completed by baywet** 2021-03-15 23:32 UTC
Labels: external, needs author feedback
